title: Elizabeth Yeo
#logo:
#description:
show_downloads: true
theme: minima

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Work Experience"
    url: "/work-experience/"

# Base URL should be empty for root domain
baseurl: ""  # Ensure this is empty or remove this line if it's set
permalink: /:categories/:year/:month/:day/:title/
